name: neet-code-katas-dev-env

services:

  dev:
    build:
      context: .
      dockerfile: dockerfile
    image: neet-code-katas-dev-img
    container_name: neet-code-katas-dev-container
    user: node
    volumes:
      - ../:/workspace:cached
      - ${HOME}/.local/share/pnpm:/home/node/.local/share/pnpm:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
